image: node:latest

stages:
  - build
  - test

cache:
    paths:
        - web_application/node_modules/

install_dependencies:
    stage: build
    script:
        - cd web_application
        - npm install
    artifacts:
        paths:
            - node_modules/

testing_testing:
    stage: test
    script:
        - cd web_application
        - npm test
