stages:
  - install
  - test
  - build
  - deploy

image: node:12

Install:
  stage: install
  interruptible: true
  only:
    - merge_requests
    - master
    - web
    - schedules
  cache:
    key:
      files:
        - web_application/package-lock.json
    paths:
      - web_application/.npm/
  artifacts:
    paths:
      - web_application/node_modules
    expire_in: 1 day
  script:
    - cd web_application
    - npm ci --cache .npm --prefer-offline

Test:
  stage: test
  dependencies:
    - Install
  interruptible: true
  only:
    - merge_requests
    - master
    - web
    - schedules
  script:
    - cd web_application
    - npm test -- --coverage
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

Build Site:
  stage: build
  dependencies:
    - Install
    - Test
  interruptible: true
  only:
    - merge_requests
    - master
    - web
    - schedules
  script:
    - cd web_application/
    - npm run build
  artifacts:
    paths:
      - web_application/dist
    expire_in: 1 day

pages:
  stage: deploy
  interruptible: true
  only:
    - master
  dependencies:
    - Build Site
  script:
    - rm -rf public
    - mv web_application/dist/  public/
  artifacts:
    paths:
      - public
