@startsalt
{
{T
 + History

 + Launch

 ++ Pre Flight Checks
 +++ Hardware
 +++ Baromter
 +++ Weather Service
 +++ Projected Landing

 ++ Map
 +++ GPS
 +++ Accelerometer

 ++ Position
 +++ Acceleration
 +++ Velocity

 ++ Phases
 +++ History
 +++ Current Phase

 ++ Battery
 +++ Charge
 +++ Temperature
 +++ Voltage
 +++ Current
 +++ Resistance
}
}
@endsalt
