@startuml
class MissionControl {
    Model: Model
    List<View>: views
    Controller: controller
}

class View {
  goNoGo: GoNoGoView
  map: MapView
  phase: PhaseView
  readings: ReadingsView
}

class Model {
  rocketLocation: Location
  rocketVector: Vector
  rocketAltitude: float
  rocketVelocity: float

  void updateRocket()
  void runSimulations()
}

class Controller {
  void sendNoGo()
  void sendGo()
  void sendLaunchImminent()
  Vector getLaunchAngle()
  void suggestLaunchAngle(Vector)
}

View "*" <-- "1" MissionControl
Model "1" <-- "1" MissionControl
Controller "1" <-- "1" MissionControl

enum RocketState {
  LIFT_OFF
  POWERED_ASCENT
  COAST
  APOGEE
  EJECTION
  RECOVERY
}

class Location {
    latitude: float
    longitude: float
}

RocketState "1" <-- "1" Model

interface Simulator {
    List<Simulation> getResults()
}
interface WeatherService {
    getWeather()
    setLocation(Location)
}
interface MapService

Simulator <-- Model
WeatherService <-- Model
MapService <-- View
@enduml
