@startuml use_case_diagram
skinparam packageStyle rectangle

actor User

rectangle MissionControl {
	(runSimulation) as RS
	(updateRocket) as UR
	(getWeather) as GW
	(primeLaunch) as PL
	(launch) as L
	(getLaunchAngle) as GLA
	(setLocation) as SL
	(getSimulationResults) as GSR
}

User --> RS
User --> UR
User --> GW
User --> PL
User --> L
User --> GLA
User --> SL
User --> GSR
User --> MS

rectangle Simulation {
	(runSimulation) <. RS
	(getResults) <. GSR
}

rectangle Rocket {
		(Prime) <. PL
		(Launch) <. L
		(suggestLaunchAngle) <. GLA
		(update) <. UR
}

rectangle WeatherService {
	(getWeather) <. GW
	(setLocation) <. SL
}

rectangle MapService {
	(getMap) <. MS
}
@enduml
